### ISSUE TITLE
Links are barely visible on highlight

### ISSUE THREAD

**Issue by WPum** [catppuccin/logseq#19] opened 2023-12-17 13:24 UTC
![image](https://github.com/catppuccin/logseq/assets/27683756/788c41ae-ead7-4782-b0df-ed1d064437c0)

**Comment by griimick** [comment] 2023-12-18 22:34
Thanks for reporting this. Will include fix for this in holiday update as a lot of other elements have broken after recent logseq update.

**Comment by mwidmann** [comment] 2024-01-24 11:53
May I just jump in in this. Using catppuccin-latte in light mode text selection `color` is berely legible as well.

![image](https://github.com/catppuccin/logseq/assets/251322/1466c2ce-337f-45e7-86c0-93a349432206)

So it seems the issue is related to both the dark and the light theme. The problem seems to be that the `background-color` of the selection comes from the logseq theme itself, while the `color` comes from the ctp-latte.css.

The easiest fix would be to not touch the `::selection` at all, it seems or change both the `color` and `background-color` to something that has enoug contrast to be legible.

For the time being, I added the following snippet to my custom.css

```css
::selection {
    color: inherit;
}
```

**Comment by griimick** [comment] 2024-01-24 12:11
Thanks @mwidmann for the inputs! If you would like to contribute you can create a PR, I would be happy to add this. Otherwise, I have a few more fixes along with this on the way, just haven't got the time to make a release yet.

**Comment by mwidmann** [comment] 2024-01-24 12:56
I created a pull request https://github.com/catppuccin/logseq/pull/21

**Closed** 2024-01-24 13:00 UTC
